### ISSUE TITLE
05.11.16

### ISSUE THREAD

**Issue by simplydesigner** [Balanar300hp/shared_ptr#1]
- [x] [1](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L7)
- [x] [2](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L48)
- [x] [через swap](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L52)
- [x] [4](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L72)
- [x] [добавьте проверку с генерацией исключения](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L95)
- [x] [добавьте проверку с генерацией исключения](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L102)
- [x] [исправьте форматирование](https://github.com/Balanar300hp/shared_ptr/blob/d54aa28909ca7232ba03ebe1e532c30cd3a698db/include/shared_ptr.hpp#L94-L105)

**Comment by kayrosik** [comment]
исправил
